import i18n from "@/lang";
/* eslint-disable */
tinymce.addI18n('zh_CN',{
"Redo":i18n.t('editorModule.redo'),
"Undo":i18n.t('editorModule.undo'),
"Cut":i18n.t('editorModule.cut'),
"Copy":i18n.t('editorModule.copy'),
"Paste":i18n.t('editorModule.paste'),
"Select all":i18n.t('editorModule.selectAll'),
"New document":i18n.t('editorModule.newDocument'),
"Ok":i18n.t('editorModule.ok'),
"Cancel":i18n.t('editorModule.cancel'),
"Visual aids":i18n.t('editorModule.visualAids'),
"Bold": i18n.t('editorModule.bold'),
"Italic":i18n.t('editorModule.italic'),
"Underline":i18n.t('editorModule.underline'),
"Strikethrough":i18n.t('editorModule.strikeThrough'),
"Superscript":i18n.t('editorModule.superScript'),
"Subscript": i18n.t('editorModule.subscript'),
"Clear formatting":i18n.t('editorModule.clearFormat'),
"Align left":i18n.t('editorModule.alignLeft'),
"Align center":i18n.t('editorModule.alignCenter'),
"Align right":i18n.t('editorModule.alignRight'),
"Justify":i18n.t('editorModule.justify'),
"Bullet list":i18n.t('editorModule.bulletList'),
"Numbered list":i18n.t('editorModule.numberedList'),
"Decrease indent":i18n.t('editorModule.decreaseIndent'),
"Increase indent":i18n.t('editorModule.increaseIndent'),
"Close":i18n.t('editorModule.close'),
"Formats":i18n.t('editorModule.formats'),
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.":i18n.t('editorModule.notSupport'),
"Headers":i18n.t('editorModule.headers'),
"Header 1": i18n.t('editorModule.headersOne'),
"Header 2": i18n.t('editorModule.headersTwo'),
"Header 3": i18n.t('editorModule.headersThree'),
"Header 4": i18n.t('editorModule.headersFour'),
"Header 5":i18n.t('editorModule.headersFive'),
"Header 6": i18n.t('editorModule.headersSix'),
"Headings": i18n.t('editorModule.headers'),
"Heading 1": i18n.t('editorModule.headersOne'),
"Heading 2":i18n.t('editorModule.headersTwo'),
"Heading 3":i18n.t('editorModule.headersThree'),
"Heading 4":i18n.t('editorModule.headersFour'),
"Heading 5": i18n.t('editorModule.headersFive'),
"Heading 6": i18n.t('editorModule.headersSix'),
"Preformatted": i18n.t('editorModule.preformatted'),
"Div": "Div",
"Pre": "Pre",
"Code": i18n.t('editorModule.code'),
"Paragraph":i18n.t('editorModule.paragraph'),
"Blockquote":i18n.t('editorModule.blockquote'),
"Inline":i18n.t('editorModule.inline'),
"Blocks":i18n.t('editorModule.blocks'),
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.":i18n.t('editorModule.pastePlain'),
"Fonts": i18n.t('editorModule.fonts'),
"Font Sizes": i18n.t('editorModule.fontSize'),
"Class":i18n.t('editorModule.type'),
"Browse for an image": i18n.t('editorModule.browseImage'),
"OR":i18n.t('editorModule.or'),
"Drop an image here":i18n.t('editorModule.dropImageHere'),
"Upload":i18n.t('editorModule.upload'),
"Block": i18n.t('editorModule.block'),
"Align":i18n.t('editorModule.align'),
"Default": i18n.t('editorModule.defa'),
"Circle":i18n.t('editorModule.circle'),
"Disc": i18n.t('editorModule.disc'),
"Square": i18n.t('editorModule.square'),
"Lower Alpha":i18n.t('editorModule.lowerAlpha'),
"Lower Greek":i18n.t('editorModule.lowerGreek'),
"Lower Roman":i18n.t('editorModule.lowerRoman'),
"Upper Alpha":i18n.t('editorModule.upperAlpha'),
"Upper Roman":i18n.t('editorModule.upperRoman'),
"Anchor...": i18n.t('editorModule.anchor'),
"Name":i18n.t('editorModule.name'),
"Id":i18n.t('editorModule.id'),
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.":i18n.t('editorModule.idFormat'),
"You have unsaved changes are you sure you want to navigate away?":i18n.t('editorModule.whetherLeave'),
"Restore last draft": i18n.t('editorModule.restoreDraft'),
"Special character...":i18n.t('editorModule.specialCharacter'),
"Source code":i18n.t('editorModule.sourceCode'),
"Insert\/Edit code sample":i18n.t('editorModule.insertCodeSample'),
"Language": i18n.t('editorModule.language'),
"Code sample...":i18n.t('editorModule.codeSample'),
"Color Picker":i18n.t('editorModule.colorPicker'),
"R": "R",
"G": "G",
"B": "B",
"Left to right":i18n.t('editorModule.leftToRight'),
"Right to left":i18n.t('editorModule.rightToLeft'),
"Emoticons...": i18n.t('editorModule.emoticons'),
"Metadata and Document Properties":i18n.t('editorModule.metadataDocument'),
"Title":i18n.t('editorModule.headers'),
"Keywords":i18n.t('editorModule.keywords'),
"Description":i18n.t('editorModule.description'),
"Robots":i18n.t('editorModule.robots'),
"Author":i18n.t('editorModule.author'),
"Encoding": i18n.t('editorModule.encoding'),
"Fullscreen":i18n.t('editorModule.fullScreen'),
"Action": i18n.t('editorModule.action'),
"Shortcut":i18n.t('editorModule.shortcut'),
"Help":i18n.t('editorModule.help'),
"Address":i18n.t('editorModule.address'),
"Focus to menubar":i18n.t('editorModule.focusMenubar'),
"Focus to toolbar":i18n.t('editorModule.focusToolbar'),
"Focus to element path":i18n.t('editorModule.focusElementPath'),
"Focus to contextual toolbar":i18n.t('editorModule.focusContextualToolbar'),
"Insert link (if link plugin activated)":i18n.t('editorModule.insertLinkActivated'),
"Save (if save plugin activated)":i18n.t('editorModule.saveActivated'),
"Find (if searchreplace plugin activated)":i18n.t('editorModule.findActivated'),
"Plugins installed ({0}):":i18n.t('editorModule.pluginsInstalled'),
"Premium plugins:": i18n.t('editorModule.premiumPlugins'),
"Learn more...":i18n.t('editorModule.learnMore'),
"You are using {0}": i18n.t('editorModule.youAreUsing'),
"Plugins":i18n.t('editorModule.plugins'),
"Handy Shortcuts": i18n.t('editorModule.shortcut'),
"Horizontal line":i18n.t('editorModule.horizontalLine'),
"Insert\/edit image":i18n.t('editorModule.insertEditImage'),
"Image description":i18n.t('editorModule.imageDescr'),
"Source":i18n.t('editorModule.address'),
"Dimensions": i18n.t('editorModule.dimensions'),
"Constrain proportions": i18n.t('editorModule.constrainProportions'),
"General":i18n.t('editorModule.general'),
"Advanced":i18n.t('editorModule.advanced'),
"Style": i18n.t('editorModule.style'),
"Vertical space":i18n.t('editorModule.verticalSpace'),
"Horizontal space":i18n.t('editorModule.horizontalSpace'),
"Border":i18n.t('editorModule.border'),
"Insert image":i18n.t('editorModule.insertImage'),
"Image...":i18n.t('editorModule.img'),
"Image list":i18n.t('editorModule.imgList'),
"Rotate counterclockwise":i18n.t('editorModule.rotateCounterclockwise'),
"Rotate clockwise":i18n.t('editorModule.rotateClockwise'),
"Flip vertically":i18n.t('editorModule.flipVertically'),
"Flip horizontally":i18n.t('editorModule.flipHorizontally'),
"Edit image":i18n.t('editorModule.editImage'),
"Image options":i18n.t('editorModule.imageOptions'),
"Zoom in": i18n.t('editorModule.zoomIn'),
"Zoom out": i18n.t('editorModule.zoomOut'),
"Crop":i18n.t('editorModule.crop'),
"Resize":i18n.t('editorModule.resize'),
"Orientation": i18n.t('editorModule.orientation'),
"Brightness": i18n.t('editorModule.brightness'),
"Sharpen":i18n.t('editorModule.sharpen'),
"Contrast":i18n.t('editorModule.contrast'),
"Color levels": i18n.t('editorModule.colorLevels'),
"Gamma": i18n.t('editorModule.gamma'),
"Invert": i18n.t('editorModule.invert'),
"Apply":i18n.t('editorModule.apply'),
"Back": i18n.t('editorModule.back'),
"Insert date\/time":  i18n.t('editorModule.insertDateTime'),
"Date\/time": i18n.t('editorModule.dateTime'),
"Insert\/Edit Link":i18n.t('editorModule.insertEditLink'),
"Insert\/edit link": i18n.t('editorModule.insertEditLink'),
"Text to display": i18n.t('editorModule.textDisplay'),
"Url":i18n.t('editorModule.address'),
"Open link in...":i18n.t('editorModule.openLink'),
"Current window":i18n.t('editorModule.currentWindow'),
"None": i18n.t('editorModule.none'),
"New window": i18n.t('editorModule.newWindow'),
"Remove link":i18n.t('editorModule.removeLink'),
"Anchors":i18n.t('editorModule.anchors'),
"Link...":i18n.t('editorModule.link'),
"Paste or type a link":i18n.t('editorModule.pasteTypeLink'),
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?":i18n.t('editorModule.needAddMilto'),
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?":i18n.t('editorModule.needAddHttp'),
"Link list":i18n.t('editorModule.linkList'),
"Insert video":i18n.t('editorModule.insertVideo'),
"Insert\/edit video": i18n.t('editorModule.insertEditVideo'),
"Insert\/edit media": i18n.t('editorModule.insertEditMedia'),
"Alternative source":i18n.t('editorModule.alternativeSource'),
"Alternative source URL": i18n.t('editorModule.alternativeSourceUrl'),
"Media poster (Image URL)":i18n.t('editorModule.mediaPoster'),
"Paste your embed code below:": i18n.t('editorModule.pasteEmbedCodeBelow'),
"Embed":i18n.t('editorModule.embed'),
"Media...": i18n.t('editorModule.mediaMore'),
"Nonbreaking space":i18n.t('editorModule.nonbreakSpace'),
"Page break":i18n.t('editorModule.pageBreak'),
"Paste as text": i18n.t('editorModule.pasteText'),
"Preview":i18n.t('editorModule.preview'),
"Print...": i18n.t('editorModule.printMore'),
"Save": i18n.t('editorModule.save'),
"Find": i18n.t('editorModule.find'),
"Replace with": i18n.t('editorModule.replaceWith'),
"Replace": i18n.t('editorModule.replace'),
"Replace all": i18n.t('editorModule.replaceAll'),
"Previous":i18n.t('editorModule.previous'),
"Next": i18n.t('editorModule.next'),
"Find and replace...": i18n.t('editorModule.findReplace'),
"Could not find the specified string.": i18n.t('editorModule.notFindSpecifiedString'),
"Match case":i18n.t('editorModule.matchCase'),
"Find whole words only":i18n.t('editorModule.findWholeWordsOnly'),
"Spell check": i18n.t('editorModule.spellCheck'),
"Ignore": i18n.t('editorModule.ignore'),
"Ignore all": i18n.t('editorModule.ignoreAll'),
"Finish":i18n.t('editorModule.finish'),
"Add to Dictionary":i18n.t('editorModule.addDictionary'),
"Insert table": i18n.t('editorModule.insertTable'),
"Table properties": i18n.t('editorModule.tableProperties'),
"Delete table": i18n.t('editorModule.deleteTable'),
"Cell": i18n.t('editorModule.cell'),
"Row":i18n.t('editorModule.row'),
"Column":i18n.t('editorModule.column'),
"Cell properties":i18n.t('editorModule.cellProperties'),
"Merge cells": i18n.t('editorModule.mergeCells'),
"Split cell": i18n.t('editorModule.splitCell'),
"Insert row before":i18n.t('editorModule.insertRowBefore'),
"Insert row after":i18n.t('editorModule.insertRowAfter'),
"Delete row": i18n.t('editorModule.deleteRow'),
"Row properties": i18n.t('editorModule.rowProperties'),
"Cut row":i18n.t('editorModule.cutRow'),
"Copy row": i18n.t('editorModule.copyRow'),
"Paste row before": i18n.t('editorModule.pasteRowBefore'),
"Paste row after": i18n.t('editorModule.pasteRowAfter'),
"Insert column before": i18n.t('editorModule.insertColumnBefore'),
"Insert column after": i18n.t('editorModule.insertColumnAfter'),
"Delete column":i18n.t('editorModule.deleteColumn'),
"Cols":i18n.t('editorModule.column'),
"Rows":i18n.t('editorModule.row'),
"Width":i18n.t('editorModule.width'),
"Height": i18n.t('editorModule.height'),
"Cell spacing": i18n.t('editorModule.cellSpacing'),
"Cell padding": i18n.t('editorModule.cellPadding'),
"Show caption": i18n.t('editorModule.showCaption'),
"Left": i18n.t('editorModule.left'),
"Center": i18n.t('editorModule.center'),
"Right": i18n.t('editorModule.right'),
"Cell type": i18n.t('editorModule.cellType'),
"Scope": i18n.t('editorModule.scope'),
"Alignment": i18n.t('editorModule.alignment'),
"H Align":i18n.t('editorModule.hAlign'),
"V Align":i18n.t('editorModule.vAlign'),
"Top": i18n.t('editorModule.top'),
"Middle": i18n.t('editorModule.middle'),
"Bottom": i18n.t('editorModule.bottom'),
"Header cell":i18n.t('editorModule.headerCell'),
"Row group":i18n.t('editorModule.rowGroup'),
"Column group":i18n.t('editorModule.columnGroup'),
"Row type":i18n.t('editorModule.rowType'),
"Header": i18n.t('editorModule.header'),
"Body":i18n.t('editorModule.body'),
"Footer": i18n.t('editorModule.footer'),
"Border color": i18n.t('editorModule.borderColor'),
"Insert template...": i18n.t('editorModule.insertTemplateMore'),
"Templates":i18n.t('editorModule.template'),
"Template":i18n.t('editorModule.templates'),
"Text color": i18n.t('editorModule.textColor'),
"Background color":i18n.t('editorModule.bgColor'),
"Custom...": i18n.t('editorModule.custom'),
"Custom color": i18n.t('editorModule.customColor'),
"No color": i18n.t('editorModule.noColor'),
"Remove color": i18n.t('editorModule.removeColor'),
"Table of Contents":i18n.t('editorModule.tableContents'),
"Show blocks":i18n.t('editorModule.showBlocks'),
"Show invisible characters":i18n.t('editorModule.showInvisibleCharacters'),
"Word count":i18n.t('editorModule.wordCount'),
"Count": i18n.t('editorModule.count'),
"Document": i18n.t('editorModule.documents'),
"Selection":i18n.t('editorModule.selection'),
"Words":i18n.t('editorModule.words'),
"Words: {0}": i18n.t('editorModule.wordsZero'),
"{0} words":i18n.t('editorModule.zeroWords'),
"File": i18n.t('editorModule.file'),
"Edit": i18n.t('editorModule.edit'),
"Insert": i18n.t('editorModule.insert'),
"View": i18n.t('editorModule.view'),
"Format":i18n.t('editorModule.format'),
"Table":i18n.t('editorModule.table'),
"Tools":i18n.t('editorModule.tools'),
"Powered by {0}": i18n.t('editorModule.poweredByZero'),
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": i18n.t('editorModule.editAreaShortcutKeys'),
"Image title": i18n.t('editorModule.imageTitle'),
"Border width": i18n.t('editorModule.borderWidth'),
"Border style": i18n.t('editorModule.borderStyle'),
"Error": i18n.t('editorModule.error'),
"Warn": i18n.t('editorModule.warn'),
"Valid": i18n.t('editorModule.valid'),
"To open the popup, press Shift+Enter": i18n.t('editorModule.shiftEnter'),
"Rich Text Area. Press ALT-0 for help.": i18n.t('editorModule.richTextArea'),
"System Font": i18n.t('editorModule.systemFont'),
"Failed to upload image: {0}":i18n.t('editorModule.failedUploadImage'),
"Failed to load plugin: {0} from url {1}": i18n.t('editorModule.failedLoadPluginOne'),
"Failed to load plugin url: {0}": i18n.t('editorModule.failedLoadPluginZero'),
"Failed to initialize plugin: {0}": i18n.t('editorModule.failedInitializePlugin'),
"example": i18n.t('editorModule.example'),
"Search":i18n.t('editorModule.search'),
"All": i18n.t('editorModule.all'),
"Currency":i18n.t('editorModule.currency'),
"Text": i18n.t('editorModule.text'),
"Quotations":i18n.t('editorModule.quotations'),
"Mathematical":i18n.t('editorModule.mathematical'),
"Extended Latin":i18n.t('editorModule.extendedLatin'),
"Symbols": i18n.t('editorModule.symbols'),
"Arrows": i18n.t('editorModule.arrows'),
"User Defined": i18n.t('editorModule.userDefined'),
"dollar sign":i18n.t('editorModule.dollarSign'),
"currency sign":i18n.t('editorModule.currencySign'),
"euro-currency sign": i18n.t('editorModule.eurocurrencySign'),
"colon sign":i18n.t('editorModule.colonSign'),
"cruzeiro sign":i18n.t('editorModule.cruzeiroSign'),
"french franc sign": i18n.t('editorModule.frenchFrancSign'),
"lira sign": i18n.t('editorModule.liraSign'),
"mill sign": i18n.t('editorModule.millSign'),
"naira sign": i18n.t('editorModule.nairaSign'),
"peseta sign": i18n.t('editorModule.pesetaSign'),
"rupee sign": i18n.t('editorModule.rupeeSign'),
"won sign": i18n.t('editorModule.wonSign'),
"new sheqel sign": i18n.t('editorModule.newSheqelSign'),
"dong sign": i18n.t('editorModule.dongSign'),
"kip sign": i18n.t('editorModule.kipSign'),
"tugrik sign": i18n.t('editorModule.tugrikSign'),
"drachma sign": i18n.t('editorModule.drachmaSign'),
"german penny symbol": i18n.t('editorModule.germanPennySymbol'),
"peso sign":  i18n.t('editorModule.pesoSign'),
"guarani sign": i18n.t('editorModule.guaraniSign'),
"austral sign": i18n.t('editorModule.australSign'),
"hryvnia sign": i18n.t('editorModule.hryvniaSign'),
"cedi sign": i18n.t('editorModule.cediSign'),
"livre tournois sign": i18n.t('editorModule.livreTournoisSign'),
"spesmilo sign": i18n.t('editorModule.spesmiloSign'),
"tenge sign": i18n.t('editorModule.tengeSign'),
"indian rupee sign":i18n.t('editorModule.indianRupeeSign'),
"turkish lira sign": i18n.t('editorModule.turkishLiraSign'),
"nordic mark sign":i18n.t('editorModule.nordicMarkSign'),
"manat sign": i18n.t('editorModule.manatSign'),
"ruble sign":i18n.t('editorModule.rubleSign'),
"yen character":i18n.t('editorModule.yenCharacter'),
"yuan character":i18n.t('editorModule.yuanCharacter'),
"yuan character, in hong kong and taiwan": i18n.t('editorModule.hongKongTaiwan'),
"yen\/yuan character variant one": i18n.t('editorModule.yuanCharacterVariant'),
"Loading emoticons...":i18n.t('editorModule.loadEmoticons'),
"Could not load emoticons": i18n.t('editorModule.notLoadEmoticons'),
"People": i18n.t('editorModule.people'),
"Animals and Nature": i18n.t('editorModule.animalsNature'),
"Food and Drink":i18n.t('editorModule.foodDrink'),
"Activity":i18n.t('editorModule.activity'),
"Travel and Places": i18n.t('editorModule.travelPlaces'),
"Objects":i18n.t('editorModule.objects'),
"Flags": i18n.t('editorModule.flags'),
"Characters": i18n.t('editorModule.characters'),
"Characters (no spaces)": i18n.t('editorModule.charactersNoSpaces'),
"{0} characters":i18n.t('editorModule.zeroCharacters'),
"Error: Form submit field collision.": i18n.t('editorModule.hintFieldCollision'),
"Error: No form element found.": i18n.t('editorModule.hintNoForm'),
"Update":i18n.t('editorModule.update'),
"Color swatch":i18n.t('editorModule.colorSwatch'),
"Turquoise": i18n.t('editorModule.turquoise'),
"Green": i18n.t('editorModule.green'),
"Blue": i18n.t('editorModule.blue'),
"Purple": i18n.t('editorModule.purple'),
"Navy Blue": i18n.t('editorModule.navyBlue'),
"Dark Turquoise": i18n.t('editorModule.darkTurquoise'),
"Dark Green":i18n.t('editorModule.darkGreen'),
"Medium Blue": i18n.t('editorModule.mediumBlue'),
"Medium Purple": i18n.t('editorModule.mediumPurple'),
"Midnight Blue": i18n.t('editorModule.midnightBlue'),
"Yellow":  i18n.t('editorModule.yellow'),
"Orange": i18n.t('editorModule.orange'),
"Red": i18n.t('editorModule.red'),
"Light Gray": i18n.t('editorModule.lightGray'),
"Gray":  i18n.t('editorModule.gray'),
"Dark Yellow": i18n.t('editorModule.darkYellow'),
"Dark Orange": i18n.t('editorModule.darkOrange'),
"Dark Red":  i18n.t('editorModule.darkRed'),
"Medium Gray": i18n.t('editorModule.mediumGray'),
"Dark Gray": i18n.t('editorModule.darkGray'),
"Light Green": i18n.t('editorModule.lightGreen'),
"Light Yellow": i18n.t('editorModule.lightYellow'),
"Light Red": i18n.t('editorModule.lightRed'),
"Light Purple": i18n.t('editorModule.lightPurple'),
"Light Blue": i18n.t('editorModule.lightBlue'),
"Dark Purple": i18n.t('editorModule.darkPurple'),
"Dark Blue": i18n.t('editorModule.darkBlue'),
"Black": i18n.t('editorModule.black'),
"White": i18n.t('editorModule.white'),
"Switch to or from fullscreen mode": i18n.t('editorModule.switchFullscreen'),
"Open help dialog":  i18n.t('editorModule.openHelpDialog'),
"history":  i18n.t('editorModule.history'),
"styles": i18n.t('editorModule.styles'),
"formatting": i18n.t('editorModule.formatting'),
"alignment":i18n.t('editorModule.alignment'),
"indentation": i18n.t('editorModule.indentation'),
"permanent pen": i18n.t('editorModule.permanentPen'),
"comments": i18n.t('editorModule.comments'),
"Format Painter": i18n.t('editorModule.formatPainter'),
"Insert\/edit iframe":i18n.t('editorModule.insertEditIframe'),
"Capitalization":i18n.t('editorModule.capitalization'),
"lowercase":i18n.t('editorModule.lowercase'),
"UPPERCASE":i18n.t('editorModule.capitalization'),
"Title Case": i18n.t('editorModule.titleCase'),
"Permanent Pen Properties":i18n.t('editorModule.permanentPenOne'),
"Permanent pen properties...": i18n.t('editorModule.permanentPenTwo'),
"Font":i18n.t('editorModule.fonts'),
"Size": i18n.t('editorModule.fontSize'),
"More...": i18n.t('editorModule.more'),
"Spellcheck Language": i18n.t('editorModule.spellcheckLanguage'),
"Select...": i18n.t('editorModule.select'),
"Preferences": i18n.t('editorModule.preferences'),
"Yes": i18n.t('editorModule.yes'),
"No": i18n.t('editorModule.no'),
"Keyboard Navigation":i18n.t('editorModule.keyboardNavigation'),
"Version":i18n.t('editorModule.version'),
"Anchor":i18n.t('editorModule.anchors'),
"Special character": i18n.t('editorModule.specialCharacter'),
"Code sample":i18n.t('editorModule.codeSample'),
"Color": i18n.t('editorModule.color'),
"Emoticons": i18n.t('editorModule.emoticons'),
"Document properties": i18n.t('editorModule.documentProperties'),
"Image":i18n.t('editorModule.image'),
"Insert link": i18n.t('editorModule.insertLink'),
"Target": i18n.t('editorModule.target'),
"Link": i18n.t('editorModule.link'),
"Poster": i18n.t('editorModule.poster'),
"Media": i18n.t('editorModule.media'),
"Print": i18n.t('editorModule.print'),
"Prev": i18n.t('editorModule.previous'),
"Find and replace":i18n.t('editorModule.findReplace'),
"Whole words": i18n.t('editorModule.findWholeWordsOnly'),
"Spellcheck": i18n.t('editorModule.spellCheck'),
"Caption":i18n.t('editorModule.headers'),
"Insert template": i18n.t('editorModule.insertTemplate'),
});